services:
  web:
    build:
      args:
        user: 'sunday'
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: ./docker-compose/coolify.Dockerfile
    image: sunday-image
    container_name: sunday-app
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - ./docker-compose/web/timezone:/etc/timezone
      - './storage:/var/www/html/storage'
    environment:
      AUTORUN_ENABLED: true
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  task:
    image: sunday-image
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    environment:
      PHP_PFM_POOL_NAME: "sunday_task"
    depends_on:
      - web
  queue:
    image: sunday-image
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    environment:
      PHP_FPM_POOL_NAME: "sunday_queue"
    depends_on:
      - web



